Implement RRT and RRT*
pranavjad/vamp pull request #1
Opened 2024-08-25 16:31 UTC by pranavjad

2024-08-26 13:36 UTC, zkingston requested changes
Some initial comments, make sure formatting is good and that you are following the general coding style of the rest of the project. I'd also just remove RRT and keep only RRT* for the actual contribution.

2024-08-26 13:36 UTC, zkingston commented on .vscode/c_cpp_properties.json
Remove this file and put it in the .gitignore

2024-08-26 13:36 UTC, zkingston commented on .vscode/settings.json
Remove this file and put it in the .gitignore

2024-08-26 13:36 UTC, zkingston commented on .vscode/tasks.json
Same, remove and ignore

2024-08-26 13:36 UTC, zkingston commented on scripts/ao_benchmark.py
> +print(np.sqrt(sum([(start[i] - goal[i])**2 for i in range(len(start))])))
Remove

2024-08-26 13:36 UTC, zkingston commented on scripts/ao_benchmark.py
Make sure to run yapf formatting

2024-08-26 13:36 UTC, zkingston commented on scripts/ao_benchmark.py
> +    plan_settings.range = 3.0
Make a CL parameter

2024-08-26 13:36 UTC, zkingston commented on scripts/flying_sphere.py
Can you move to the PyBulletSimulator class implementation and add a function "wait()" or something equivalent?

2024-08-26 13:36 UTC, zkingston commented on scripts/sphere_cage_example.py
> +print("optimal cost: ", np.sqrt(sum([(a[i] - b[i])**2 for i in range(len(a))])))
Remove

2024-08-26 13:36 UTC, zkingston commented on scripts/sphere_cage_example.py
> +    # plan_settings.rewire_factor = 3.0
Remove

2024-08-26 13:36 UTC, zkingston commented on scripts/sphere_cage_example.py
> +    # plan_settings.rewire_factor = 3.0
Should be able to set these via command line, please check if that works.

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt.hh
For the actual PR I think we remove vanilla RRT, I don't want to clutter up the VAMP codebase with every SBMP like OMPL

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +            const auto add_edge = [&parent, &children](std::size_t parent_node, std::size_t child_node) -> void
No need to specify -> void at the end

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                children[parent_node].push_back(child_node);
Use emplace_back

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
Run clang-format

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +            std::function<void(std::size_t)> update_children = [&cost, &children, &buffer_index, &update_children](std::size_t idx)
const auto?

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                    std::size_t card = tree.size() + 1; //plus 1 to account for the new configuration not inserted yet
const

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                    std::size_t card = tree.size() + 1; //plus 1 to account for the new configuration not inserted yet
to all these values, actually

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                    float free_volume = space_measure();
make static const at top, no need to compute each loop

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                    float free_volume = space_measure();
for the constant variables, anyway

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                        if ((cur_cost < min_cost) && collision_free[idx]) {
use `and` rather than `&&`

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                        if ((cur_cost < min_cost) && collision_free[idx]) {
Move collision_free test first for early exit

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                                // std::cout << "New best path found with cost: " << best_path_cost << " at iter " << iter << std::endl;
remove

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +        }
constexpr?

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +            float unit_ball_volume = unitNballMeasure(dimension);
constexpr? move to static?

2024-08-26 13:36 UTC, zkingston commented on src/impl/vamp/planning/rrt_star.hh
> +                    if (!settings.force_max_iters && goal_reached) break;
`not` and `and`

2024-08-26 13:36 UTC, zkingston commented on src/vamp/pybullet_interface.py
> +        # with DisableRendering(self.client), RedirectStream(sys.stdout), RedirectStream(sys.stderr):
Add back in - keep it the same for now but we need to figure out the Mac rendering issues later.

2024-09-05 03:51 UTC, pranavjad commented
Created a new PR since this branch as a whole bunch of other stuff.

2024-09-05 03:51 UTC, closed without merging